(() => {
  const API='http://127.0.0.1:8798';
  const page=document.body.dataset.navPage;
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function get(path,options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'接口请求失败');return d}
  function fail(e){$('#page-loading')?.remove();$('#page-error').innerHTML=`<div class="card" style="padding:16px;color:#b84b4b;background:#fff1f1">新版数据加载失败：${esc(e.message)}。请确认新版服务已启动：127.0.0.1:8798。</div>`}
  function render(title,html){$('#page-loading')?.remove();$('#page-content').innerHTML=`<section class="card full-card"><div class="card-head"><div><h2>${title}</h2><p>以下内容来自新版独立数据库，不读取原版项目数据。</p></div></div><div class="table-wrap">${html}</div></section>`}
  function empty(title='还没有项目'){render(title,`<div style="padding:28px 8px"><p>这是一个全新的工作空间，目前没有项目数据。</p><a class="btn" href="new-project.html">创建第一个项目</a></div>`)}
  function projectQuery(slug,pageName){return `${pageName}?project=${encodeURIComponent(slug)}`}
  async function boot(){try{
    const ps=(await get('/api/projects')).projects;
    if(page==='projects'){
      render('项目列表',`<label>搜索项目 <input id="project-filter" placeholder="输入项目名称或 slug"></label><table class="table"><thead><tr><th>项目</th><th>类型</th><th>创建时间</th><th>数据</th><th>操作</th></tr></thead><tbody>${ps.map(x=>`<tr><td><span class="project-name">${esc(x.name)}<small>${esc(x.slug)}</small></span></td><td>${esc(x.target_type_label)}</td><td>${esc(x.created_at||'')}</td><td>${x.counts.actions} 个任务 / ${x.counts.assets} 条内容</td><td><a class="btn secondary small" href="${projectQuery(x.slug,'diagnosis.html')}">诊断</a> <button class="btn secondary small danger" data-delete="${esc(x.slug)}" data-name="${esc(x.name)}">删除项目</button></td></tr>`).join('')||'<tr><td colspan="5">暂无项目。请创建第一个项目。</td></tr>'}</tbody></table>`);
      const input=$('#project-filter'); if(input)input.oninput=()=>{const q=input.value.toLowerCase();document.querySelectorAll('.table tbody tr').forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q))};
      document.querySelectorAll('[data-delete]').forEach(btn=>{btn.onclick=async()=>{if(!confirm(`确认删除项目“${btn.dataset.name}”？该项目在新版数据库中的内容将一并删除。`))return;try{await get(`/api/projects/${encodeURIComponent(btn.dataset.delete)}`,{method:'DELETE'});location.reload()}catch(e){$('#page-error').innerHTML=`<div class="card" style="padding:12px;color:#b84b4b">删除失败：${esc(e.message)}</div>`}}});
      return;
    }
    const p=ps[0];
    if(!p){empty();return;}
    const slug=encodeURIComponent(p.slug);
    if(page==='compare'){const d=await get(`/api/projects/${slug}/compare`);render('平台对比',`<table class="table"><thead><tr><th>平台</th><th>回答数</th><th>自然提及</th><th>明确推荐</th><th>引用</th></tr></thead><tbody>${(d.platforms||[]).map(x=>`<tr><td>${esc(x.platform)}</td><td>${x.total}</td><td>${x.mentions}</td><td>${x.recommendations}</td><td>${x.citations}</td></tr>`).join('')||'<tr><td colspan="5">暂无可比较数据。新版项目创建后可在此查看。</td></tr>'}</tbody></table>`)}
    if(page==='tasks'){const d=await get(`/api/projects/${slug}/actions`);render('改善任务',`<table class="table"><thead><tr><th>任务</th><th>优先级</th><th>缺口</th><th>状态</th><th>来源</th></tr></thead><tbody>${(d.actions||[]).map(x=>`<tr><td><span class="project-name">${esc(x.title)}<small>${esc(x.description||'')}</small></span></td><td>${esc(x.priority)}</td><td>${esc(x.gap_type)}</td><td><select data-action-id="${esc(x.id)}" class="task-status"><option value="todo" ${x.status==='todo'?'selected':''}>待处理</option><option value="doing" ${x.status==='doing'?'selected':''}>处理中</option><option value="done" ${x.status==='done'?'selected':''}>已完成</option><option value="skipped" ${x.status==='skipped'?'selected':''}>暂不处理</option></select></td><td>${esc((x.source_task_ids||[]).join(', '))}</td></tr>`).join('')||'<tr><td colspan="5">暂无改善任务。</td></tr>'}</tbody></table>`);document.querySelectorAll('.task-status').forEach(el=>el.onchange=async()=>{try{await get(`/api/projects/${slug}/actions/${encodeURIComponent(el.dataset.actionId)}/status`,{method:'POST',body:JSON.stringify({status:el.value})})}catch(e){$('#page-error').innerHTML=`<div class="card" style="padding:12px;color:#b84b4b">任务状态保存失败：${esc(e.message)}</div>`}})}
    if(page==='reports'){const d=await get(`/api/projects/${slug}/reports`);render('诊断报告文件',`<table class="table"><thead><tr><th>批次</th><th>文件</th><th>大小</th><th>操作</th></tr></thead><tbody>${(d.reports||[]).map(x=>`<tr><td>${esc(x.run_id)}</td><td>${esc(x.name)}</td><td>${Math.round((x.size||0)/1024)} KB</td><td><a class="btn secondary small" href="${API}${x.url}" target="_blank">下载报告</a></td></tr>`).join('')||'<tr><td colspan="4">暂无报告文件。</td></tr>'}</tbody></table>`)}
    if(page==='platforms'){const d=await get('/api/platforms');render('平台接入状态',`<table class="table"><thead><tr><th>平台</th><th>用途</th><th>接入方式</th><th>状态</th></tr></thead><tbody>${d.platforms.map(x=>`<tr><td>${esc(x.label)}</td><td>内容发布/引用平台</td><td>${esc(x.mode)}</td><td><span class="status warn">人工门禁</span></td></tr>`).join('')}</tbody></table><p class="module-note"><b>边界：</b>新版不保存平台凭据，不自动登录或发布。</p>`)}
    if(page==='settings'){const d=await get('/api/settings');$('#page-loading')?.remove();$('#page-content').innerHTML=`<section class="card" style="padding:22px"><h2>新版工作空间设置</h2><p>设置只保存到新版独立数据库。</p><form id="settings-form"><label>工作空间名称<input name="workspace_label" value="${esc(d.settings.workspace_label)}"></label><label>默认操作人<input name="default_operator" value="${esc(d.settings.default_operator)}"></label><button class="btn" type="submit">保存设置</button><span id="save-result" class="muted" style="margin-left:10px"></span></form></section>`;$('#settings-form').onsubmit=async e=>{e.preventDefault();const payload=Object.fromEntries(new FormData(e.target));try{const x=await get('/api/settings',{method:'POST',body:JSON.stringify(payload)});$('#save-result').textContent=x.message}catch(err){$('#save-result').textContent='保存失败：'+err.message}}}
  }catch(e){fail(e)}}boot();
})();
